### ISSUE TITLE
CSS modules and RazorPages

### ISSUE THREAD

**Issue by lonix1** [Baune8D/AspNet.Frontend.Templates#2]
Can this be used to get css modules with razorpages?

I found out how to do it with a SPA, but if I'm using server-rendered pages (mvc or razorpages), is that possible somehow?

**Comment by Baune8D** [comment]
Absolutely, look at this example: [src/AspNetWebpack/Assets/views/Home/Module](https://github.com/Baune8D/AspNetWebpack/tree/master/src/AspNetWebpack/Assets/views/Home/Module)
The same files could be copied to: [src/AspNetWebpack/Assets/pages/RazorPage](https://github.com/Baune8D/AspNetWebpack/tree/master/src/AspNetWebpack/Assets/pages/RazorPage) to do the same thing in a razor page.
